//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/AIPilot.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @AIPilotControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AIPilotControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AIPilot"",
    ""maps"": [
        {
            ""name"": ""PYR"",
            ""id"": ""3123bd4c-f6ee-4201-ac8d-8b8836c15439"",
            ""actions"": [
                {
                    ""name"": ""Pitch"",
                    ""type"": ""Value"",
                    ""id"": ""3ca257ec-85ac-459a-bdea-3945e12de386"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Value"",
                    ""id"": ""f1cd0492-a55e-4091-b005-16d2c6e7fe53"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Button"",
                    ""id"": ""46d32594-52fd-46fe-9634-acfc319ec3e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e8e36c38-80f5-4202-a96e-861becb125e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slew"",
                    ""type"": ""Button"",
                    ""id"": ""2696f358-3452-4b30-a846-441f0c9da247"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Break"",
                    ""type"": ""Button"",
                    ""id"": ""351495ab-f3e6-4a41-b57d-6e35472c37d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trim"",
                    ""type"": ""Value"",
                    ""id"": ""4c8b8bd4-fc17-4156-99a7-a332b1e8c067"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""188fb67c-f990-4ead-b0b8-4ede33ef4f7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Break1"",
                    ""type"": ""Button"",
                    ""id"": ""622a2fe1-c6de-4e70-b867-dc9eb5589216"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponFire"",
                    ""type"": ""Button"",
                    ""id"": ""b38be802-591d-4eef-a389-7825b7c5da2d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CMS"",
                    ""type"": ""Button"",
                    ""id"": ""c7cc68a4-9f78-4af2-af5f-d9d383aa2f0f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""84671b50-31ce-4201-947f-715ac71b4b82"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0674d84-89b1-47fc-a203-db8097a60f08"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""23afa640-7254-4420-9d6d-fe0fd457effe"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d18b1842-b5db-4ae6-9ab0-3eda9c915a12"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fe255610-78c8-4e55-a647-f31b5241faa6"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5c4e903d-12ba-4550-88ea-6d2300280bc8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""700b1466-c268-4f86-a8ee-27411e831be4"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Slew"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00bddea8-a7ca-4335-8590-4efa2befe0bf"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Break"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ed4e188-9518-49c7-a897-eebdaf0f1310"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e70c35b-b585-4d36-a4fa-d84098ba2428"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0fa0511-a9fe-415a-b481-180c2efff0d9"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Break1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45ef3f76-834e-4d45-b86d-d5d4c25370b8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efe1feec-2655-4533-9338-b91373c39005"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CMS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PYR
        m_PYR = asset.FindActionMap("PYR", throwIfNotFound: true);
        m_PYR_Pitch = m_PYR.FindAction("Pitch", throwIfNotFound: true);
        m_PYR_Roll = m_PYR.FindAction("Roll", throwIfNotFound: true);
        m_PYR_Throttle = m_PYR.FindAction("Throttle", throwIfNotFound: true);
        m_PYR_Pause = m_PYR.FindAction("Pause", throwIfNotFound: true);
        m_PYR_Slew = m_PYR.FindAction("Slew", throwIfNotFound: true);
        m_PYR_Break = m_PYR.FindAction("Break", throwIfNotFound: true);
        m_PYR_Trim = m_PYR.FindAction("Trim", throwIfNotFound: true);
        m_PYR_Look = m_PYR.FindAction("Look", throwIfNotFound: true);
        m_PYR_Break1 = m_PYR.FindAction("Break1", throwIfNotFound: true);
        m_PYR_WeaponFire = m_PYR.FindAction("WeaponFire", throwIfNotFound: true);
        m_PYR_CMS = m_PYR.FindAction("CMS", throwIfNotFound: true);
    }

    ~@AIPilotControls()
    {
        Debug.Assert(!m_PYR.enabled, "This will cause a leak and performance issues, AIPilotControls.PYR.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PYR
    private readonly InputActionMap m_PYR;
    private List<IPYRActions> m_PYRActionsCallbackInterfaces = new List<IPYRActions>();
    private readonly InputAction m_PYR_Pitch;
    private readonly InputAction m_PYR_Roll;
    private readonly InputAction m_PYR_Throttle;
    private readonly InputAction m_PYR_Pause;
    private readonly InputAction m_PYR_Slew;
    private readonly InputAction m_PYR_Break;
    private readonly InputAction m_PYR_Trim;
    private readonly InputAction m_PYR_Look;
    private readonly InputAction m_PYR_Break1;
    private readonly InputAction m_PYR_WeaponFire;
    private readonly InputAction m_PYR_CMS;
    public struct PYRActions
    {
        private @AIPilotControls m_Wrapper;
        public PYRActions(@AIPilotControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pitch => m_Wrapper.m_PYR_Pitch;
        public InputAction @Roll => m_Wrapper.m_PYR_Roll;
        public InputAction @Throttle => m_Wrapper.m_PYR_Throttle;
        public InputAction @Pause => m_Wrapper.m_PYR_Pause;
        public InputAction @Slew => m_Wrapper.m_PYR_Slew;
        public InputAction @Break => m_Wrapper.m_PYR_Break;
        public InputAction @Trim => m_Wrapper.m_PYR_Trim;
        public InputAction @Look => m_Wrapper.m_PYR_Look;
        public InputAction @Break1 => m_Wrapper.m_PYR_Break1;
        public InputAction @WeaponFire => m_Wrapper.m_PYR_WeaponFire;
        public InputAction @CMS => m_Wrapper.m_PYR_CMS;
        public InputActionMap Get() { return m_Wrapper.m_PYR; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PYRActions set) { return set.Get(); }
        public void AddCallbacks(IPYRActions instance)
        {
            if (instance == null || m_Wrapper.m_PYRActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PYRActionsCallbackInterfaces.Add(instance);
            @Pitch.started += instance.OnPitch;
            @Pitch.performed += instance.OnPitch;
            @Pitch.canceled += instance.OnPitch;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @Throttle.started += instance.OnThrottle;
            @Throttle.performed += instance.OnThrottle;
            @Throttle.canceled += instance.OnThrottle;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Slew.started += instance.OnSlew;
            @Slew.performed += instance.OnSlew;
            @Slew.canceled += instance.OnSlew;
            @Break.started += instance.OnBreak;
            @Break.performed += instance.OnBreak;
            @Break.canceled += instance.OnBreak;
            @Trim.started += instance.OnTrim;
            @Trim.performed += instance.OnTrim;
            @Trim.canceled += instance.OnTrim;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Break1.started += instance.OnBreak1;
            @Break1.performed += instance.OnBreak1;
            @Break1.canceled += instance.OnBreak1;
            @WeaponFire.started += instance.OnWeaponFire;
            @WeaponFire.performed += instance.OnWeaponFire;
            @WeaponFire.canceled += instance.OnWeaponFire;
            @CMS.started += instance.OnCMS;
            @CMS.performed += instance.OnCMS;
            @CMS.canceled += instance.OnCMS;
        }

        private void UnregisterCallbacks(IPYRActions instance)
        {
            @Pitch.started -= instance.OnPitch;
            @Pitch.performed -= instance.OnPitch;
            @Pitch.canceled -= instance.OnPitch;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @Throttle.started -= instance.OnThrottle;
            @Throttle.performed -= instance.OnThrottle;
            @Throttle.canceled -= instance.OnThrottle;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Slew.started -= instance.OnSlew;
            @Slew.performed -= instance.OnSlew;
            @Slew.canceled -= instance.OnSlew;
            @Break.started -= instance.OnBreak;
            @Break.performed -= instance.OnBreak;
            @Break.canceled -= instance.OnBreak;
            @Trim.started -= instance.OnTrim;
            @Trim.performed -= instance.OnTrim;
            @Trim.canceled -= instance.OnTrim;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Break1.started -= instance.OnBreak1;
            @Break1.performed -= instance.OnBreak1;
            @Break1.canceled -= instance.OnBreak1;
            @WeaponFire.started -= instance.OnWeaponFire;
            @WeaponFire.performed -= instance.OnWeaponFire;
            @WeaponFire.canceled -= instance.OnWeaponFire;
            @CMS.started -= instance.OnCMS;
            @CMS.performed -= instance.OnCMS;
            @CMS.canceled -= instance.OnCMS;
        }

        public void RemoveCallbacks(IPYRActions instance)
        {
            if (m_Wrapper.m_PYRActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPYRActions instance)
        {
            foreach (var item in m_Wrapper.m_PYRActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PYRActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PYRActions @PYR => new PYRActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IPYRActions
    {
        void OnPitch(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnThrottle(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnSlew(InputAction.CallbackContext context);
        void OnBreak(InputAction.CallbackContext context);
        void OnTrim(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnBreak1(InputAction.CallbackContext context);
        void OnWeaponFire(InputAction.CallbackContext context);
        void OnCMS(InputAction.CallbackContext context);
    }
}
